### ISSUE TITLE
MP3 support ?

### ISSUE THREAD

**Issue by anthonymasure** [dpschen/kirby-plyrtag#1]
The plugin doesn't seem to work for MP3 files ?

**Comment by dpschen** [comment]
You are right!
Is now fixed in c93414d

**Comment by anthonymasure** [comment]
Now I have this error in the last version: 
Parse error: syntax error, unexpected '}' in plyrtag.php on line 87

**Comment by dpschen** [comment]
Ooops missed a semicolon. Sorry :)
Tried again in 6ee300f81e74743247f869c52862d815161590df
